# Generated by Django 5.2.8 on 2026-01-21 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='重量(kg)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='過磅時間')),
                ('is_transported', models.BooleanField(default=False, verbose_name='是否被載運')),
                ('transport_record_id', models.IntegerField(blank=True, null=True, verbose_name='載運紀錄ID')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('location_id', models.IntegerField(verbose_name='定點ID')),
                ('dept_id', models.IntegerField(verbose_name='部門ID')),
                ('waste_type_id', models.IntegerField(verbose_name='廢棄物種類ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_records', to=settings.AUTH_USER_MODEL, verbose_name='過磅人員')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_records', to=settings.AUTH_USER_MODEL, verbose_name='更新人員')),
            ],
            options={
                'verbose_name': '即時廢棄物紀錄',
                'db_table': 'realtime_record',
            },
        ),
    ]
