# Generated by Django 6.0.1 on 2026-01-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0002_clearagency_department_group_locationpoint_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clearagency',
            options={'verbose_name': '清理機構'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部門'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '使用者群組'},
        ),
        migrations.AlterModelOptions(
            name='locationpoint',
            options={'verbose_name': '定點'},
        ),
        migrations.AlterModelOptions(
            name='processagency',
            options={'verbose_name': '處理機構'},
        ),
        migrations.AlterModelOptions(
            name='transportrecord',
            options={'verbose_name': '載運紀錄'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '使用者'},
        ),
        migrations.AlterModelOptions(
            name='wasterecord',
            options={'verbose_name': '廢棄物紀錄'},
        ),
        migrations.AlterModelOptions(
            name='wastetype',
            options={'verbose_name': '廢棄物種類'},
        ),
        migrations.AlterModelTable(
            name='clearagency',
            table='clear_agency',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
        migrations.AlterModelTable(
            name='locationpoint',
            table='location_point',
        ),
        migrations.AlterModelTable(
            name='processagency',
            table='process_agency',
        ),
        migrations.AlterModelTable(
            name='transportrecord',
            table='transport_record',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='wasterecord',
            table='waste_record',
        ),
        migrations.AlterModelTable(
            name='wastetype',
            table='waste_type',
        ),
    ]
