# Generated by Django 6.0.1 on 2026-01-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0003_alter_clearagency_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_code',
            new_name='dept_code',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department_id',
            new_name='dept_id',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department_name',
            new_name='dept_name',
        ),
        migrations.RenameField(
            model_name='wastetype',
            old_name='WasteType_id',
            new_name='waste_type_id',
        ),
        migrations.RenameField(
            model_name='wastetype',
            old_name='WasteType_name',
            new_name='waste_type_name',
        ),
    ]
