# Generated by Django 6.0.1 on 2026-01-24 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0004_rename_department_code_department_dept_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterecord',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_records', to=settings.AUTH_USER_MODEL, verbose_name='過磅人員'),
        ),
        migrations.AlterField(
            model_name='wasterecord',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_records', to=settings.AUTH_USER_MODEL, verbose_name='更新人員'),
        ),
        migrations.DeleteModel(
            name='RealtimeRecord',
        ),
    ]
