# Generated by Django 6.0.1 on 2026-01-24 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0005_alter_wasterecord_creator_alter_wasterecord_updater_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AlterField(
            model_name='transportrecord',
            name='settlement_staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_records', to=settings.AUTH_USER_MODEL, verbose_name='過磅人員'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
