# Generated by Django 6.0.1 on 2026-01-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0006_remove_user_group_remove_user_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationpoint',
            old_name='location_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='locationpoint',
            old_name='location_name',
            new_name='name',
        ),
    ]
