# Generated by Django 6.0.1 on 2026-01-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0007_rename_location_id_locationpoint_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dept_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='locationpoint',
            old_name='location_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='locationpoint',
            old_name='created_at',
            new_name='created_time',
        ),
    ]
