# Generated by Django 6.0.1 on 2026-01-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0008_rename_dept_code_department_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clearagency',
            old_name='clearAgency_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='clearagency',
            old_name='clearAgency_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='clearagency',
            old_name='clearAgency_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='processagency',
            old_name='processAgency_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='processagency',
            old_name='processAgency_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='processagency',
            old_name='processAgency_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='wasterecord',
            old_name='wasterecord_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='wastetype',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='wastetype',
            old_name='waste_type_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='wastetype',
            old_name='waste_type_name',
            new_name='name',
        ),
    ]
