# Generated by Django 6.0.1 on 2026-01-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0009_rename_clearagency_code_clearagency_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasterecord',
            name='can_delete',
        ),
    ]
