# Generated by Django 6.0.1 on 2026-01-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0013_alter_wasterecord_can_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterecord',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
    ]
