# Generated by Django 6.0.1 on 2026-01-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0014_alter_wasterecord_can_delete'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='locationpoint',
            table='location',
        ),
    ]
