# Generated by Django 6.0.1 on 2026-01-24 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0015_alter_locationpoint_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterecord',
            name='TransportRecord_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_extension.transportrecord'),
        ),
    ]
