# Generated by Django 6.0.1 on 2026-01-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0016_alter_wasterecord_transportrecord_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wasterecord',
            old_name='TransportRecord_id',
            new_name='TransportRecord',
        ),
    ]
