# Generated by Django 6.0.1 on 2026-01-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0017_rename_transportrecord_id_wasterecord_transportrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportrecord',
            old_name='clearAgency_id',
            new_name='clearAgency',
        ),
        migrations.RenameField(
            model_name='transportrecord',
            old_name='transport_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='transportrecord',
            old_name='processAgency_id',
            new_name='processAgency',
        ),
        migrations.RenameField(
            model_name='transportrecord',
            old_name='settlement_staff_id',
            new_name='settlement_staff',
        ),
    ]
