# Generated by Django 6.0.1 on 2026-01-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0018_rename_clearagency_id_transportrecord_clearagency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterecord',
            name='can_delete',
            field=models.BooleanField(default=True),
        ),
    ]
