# Generated by Django 6.0.1 on 2026-01-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0019_alter_wasterecord_can_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasterecord',
            name='can_delete',
        ),
    ]
