# Generated by Django 6.0.1 on 2026-01-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0020_remove_wasterecord_can_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterecord',
            name='can_delete',
            field=models.BooleanField(default=True),
        ),
    ]
