# Generated by Django 6.0.1 on 2026-01-26 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0021_wasterecord_can_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterecord',
            name='TransportRecord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard_extension.transportrecord'),
        ),
    ]
