# Generated by Django 6.0.1 on 2026-01-26 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0022_alter_wasterecord_transportrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrecord',
            name='settlement_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_records', to=settings.AUTH_USER_MODEL, verbose_name='結算人員'),
        ),
    ]
