# Generated by Django 6.0.1 on 2026-01-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0023_alter_transportrecord_settlement_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportrecord',
            old_name='clearAgency',
            new_name='clear_agency',
        ),
        migrations.RenameField(
            model_name='transportrecord',
            old_name='processAgency',
            new_name='process_agency',
        ),
        migrations.RenameField(
            model_name='transportrecord',
            old_name='settlement_time',
            new_name='settle_time',
        ),
        migrations.RenameField(
            model_name='transportrecord',
            old_name='settlement_staff',
            new_name='settler',
        ),
        migrations.AddField(
            model_name='transportrecord',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
