# Generated by Django 6.0.1 on 2026-01-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0024_rename_clearagency_transportrecord_clear_agency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportrecord',
            name='total_weight',
        ),
    ]
