# Generated by Django 6.0.1 on 2026-01-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0025_remove_transportrecord_total_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wasterecord',
            old_name='TransportRecord',
            new_name='transportrecord',
        ),
    ]
