# Generated by Django 6.0.1 on 2026-01-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0026_rename_transportrecord_wasterecord_transportrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasterecord',
            name='can_delete',
        ),
    ]
