# Generated by Django 6.0.1 on 2026-01-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0027_remove_wasterecord_can_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterecord',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
