# Generated by Django 6.0.1 on 2026-01-31 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0028_alter_wasterecord_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasterecord',
            name='is_expired',
        ),
    ]
