# Generated by Django 6.0.1 on 2026-02-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0029_remove_wasterecord_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterecord',
            name='waste_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='廢棄物種類'),
        ),
    ]
