# Generated by Django 6.0.1 on 2026-02-03 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0030_wasterecord_waste_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastetype',
            name='wasteRecord_id',
        ),
        migrations.AlterField(
            model_name='wasterecord',
            name='waste_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard_extension.wastetype'),
        ),
    ]
