# Generated by Django 6.0.1 on 2026-03-11 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0012_alter_wasterecord_department'),
        ('dashboard_extension', '0031_remove_wastetype_wasterecord_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterecord',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_records', to='WasteManagement.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
