# Generated by Django 6.0.1 on 2026-03-11 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0013_alter_wasterecord_waste_type'),
        ('dashboard_extension', '0032_alter_wasterecord_department_delete_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterecord',
            name='waste_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extension_types', to='WasteManagement.wastetype'),
        ),
        migrations.DeleteModel(
            name='WasteType',
        ),
    ]
