# Generated by Django 6.0.1 on 2026-03-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_extension', '0033_alter_wasterecord_waste_type_delete_wastetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportrecord',
            name='clear_agency',
        ),
        migrations.RemoveField(
            model_name='wasterecord',
            name='location',
        ),
        migrations.RemoveField(
            model_name='transportrecord',
            name='process_agency',
        ),
        migrations.RemoveField(
            model_name='transportrecord',
            name='settler',
        ),
        migrations.RemoveField(
            model_name='wasterecord',
            name='transportrecord',
        ),
        migrations.RemoveField(
            model_name='wasterecord',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='wasterecord',
            name='department',
        ),
        migrations.RemoveField(
            model_name='wasterecord',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='wasterecord',
            name='waste_type',
        ),
        migrations.DeleteModel(
            name='clearAgency',
        ),
        migrations.DeleteModel(
            name='LocationPoint',
        ),
        migrations.DeleteModel(
            name='processAgency',
        ),
        migrations.DeleteModel(
            name='TransportRecord',
        ),
        migrations.DeleteModel(
            name='WasteRecord',
        ),
    ]
