# Generated by Django 6.0.1 on 2026-04-04 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    
    dependencies = [
        ('WasteManagement', '0015_clearagency_locationpoint_processagency_and_more'),
    ]

    
    