# Generated by Django 6.0.1 on 2026-04-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0018_clearagency_locationpoint_processagency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wasterecord_new',
            options={'verbose_name': '新廢棄物紀錄', 'verbose_name_plural': '新廢棄物紀錄'},
        ),
        migrations.RemoveField(
            model_name='wasterecord_new',
            name='is_transported',
        ),
    ]
