# Generated by Django 6.0.1 on 2026-04-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0019_alter_wasterecord_new_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clearagency',
            options={'verbose_name': '清理機構', 'verbose_name_plural': '清理機構'},
        ),
        migrations.AlterModelOptions(
            name='locationpoint',
            options={'verbose_name': '定點', 'verbose_name_plural': '定點'},
        ),
        migrations.AlterModelOptions(
            name='processagency',
            options={'verbose_name': '處理機構', 'verbose_name_plural': '處理機構'},
        ),
        migrations.AlterModelOptions(
            name='transportrecord',
            options={'verbose_name': '載運紀錄', 'verbose_name_plural': '載運紀錄'},
        ),
    ]
