# Generated by Django 6.0.1 on 2026-04-29 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0020_alter_clearagency_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('overdue', '清運逾期'), ('volume', '產出量異常')], max_length=20)),
                ('weight_threshold', models.FloatField(blank=True, help_text='重量限制 (kg)', null=True)),
                ('time_frequency', models.CharField(choices=[('daily', '每日'), ('weekly', '每週'), ('monthly', '每月')], default='daily', max_length=20)),
                ('overdue_hours', models.IntegerField(blank=True, help_text='逾期小時數', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('waste_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WasteManagement.wastetype')),
            ],
        ),
    ]
