# Generated by Django 6.0.1 on 2026-04-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0021_alertconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertconfig',
            name='overdue_hours',
            field=models.IntegerField(blank=True, default=24, help_text='逾期小時數', null=True),
        ),
        migrations.AlterField(
            model_name='alertconfig',
            name='weight_threshold',
            field=models.FloatField(blank=True, default=100, help_text='重量限制 (kg)', null=True),
        ),
    ]
