# Generated by Django 6.0.1 on 2026-04-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0022_alter_alertconfig_overdue_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertconfig',
            name='weight_threshold',
        ),
        migrations.AddField(
            model_name='alertconfig',
            name='weight_max',
            field=models.FloatField(blank=True, default=100, help_text='重量最大限制 (kg)', null=True),
        ),
        migrations.AddField(
            model_name='alertconfig',
            name='weight_min',
            field=models.FloatField(blank=True, default=1, help_text='重量最小限制 (kg)', null=True),
        ),
    ]
