# Generated by Django 6.0.1 on 2026-04-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0023_remove_alertconfig_weight_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertconfig',
            name='alert_type',
        ),
    ]
