# Generated by Django 6.0.1 on 2026-05-13 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0024_remove_alertconfig_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertconfig',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_configs', to='WasteManagement.department'),
        ),
        migrations.AlterField(
            model_name='alertconfig',
            name='waste_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_configs', to='WasteManagement.wastetype'),
        ),
    ]
