# Generated by Django 6.0.1 on 2026-05-13 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0025_alertconfig_department_alter_alertconfig_waste_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterecord_new',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='過磅時間'),
        ),
        migrations.AlterField(
            model_name='wasterecord_new',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新時間'),
        ),
    ]
