# Generated by Django 6.0.1 on 2026-05-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0026_alter_wasterecord_new_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertconfig',
            name='weighting_counts',
            field=models.IntegerField(blank=True, default=3, help_text='每日過磅次數標準', null=True),
        ),
    ]
