# Generated by Django 6.0.1 on 2026-05-16 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0027_alertconfig_weighting_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterecord_new',
            name='waste_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension_types', to='WasteManagement.wastetype'),
        ),
    ]
