# Generated by Django 6.0.1 on 2026-05-16 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteManagement', '0028_alter_wasterecord_new_waste_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrecord',
            name='settle_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='結算時間'),
        ),
    ]
